SET GLOBAL event_scheduler = ON;

CREATE EVENT `LIMPA_TOKEN_EXPIRADO`
	ON SCHEDULE EVERY 1 MINUTE STARTS CURRENT_TIME() 
	ON COMPLETION PRESERVE ENABLE 
DO 
BEGIN
	DELETE FROM `Token`  WHERE UNIX_TIMESTAMP() >= UNIX_TIMESTAMP(`Token`.`date`) + `Token`.`timeout`;
END;

CREATE EVENT `LIMPA_TOKEN_EXPIRADO`
	ON SCHEDULE EVERY 1 MINUTE STARTS CURRENT_TIME()
	ON COMPLETION PRESERVE ENABLE
DO
BEGIN
	DELETE FROM `Token`  WHERE UNIX_TIMESTAMP() >= UNIX_TIMESTAMP(`Token`.`date`) + `Token`.`timeout`;
END;